### ISSUE TITLE
LBG: Incorrect Access Token hash value returned in the Access Token response's ID Token

### ISSUE THREAD

**Issue by j-ahmed** [openbankingspace/tpp-issues#10]
The `at_hash` claim that is returned in the `id_token` included in the access token response after exchanging the `authorization_code` for an `access_token` fails validation against the `access_token` value.

As per Hybrid Flow (OIDC Core) 
> If the ID Token is issued from the Authorization Endpoint with an access_token value, which is the case for the response_type value code id_token token, this is REQUIRED; otherwise, its inclusion is OPTIONAL.

This hash value supposed to be validated, and if we are unable to validate it, the integrity of the `access_token` cannot be guaranteed.

**Comment by jspaine** [comment]
This was apparently fixed yesterday, tried it earlier and it does match now.

**Comment by j-ahmed** [comment]
Yes, just got an email from them today notifying us that this is fixed. This can be closed now.
