### ISSUE TITLE
Open Banking directory is not able to issue keys

### ISSUE THREAD

**Issue by qcastel** [openbankingspace/tpp-issues#101]
The Open Banking directory is currently not able to issue keys to TPPs.

If you try to get a transport certificate for example, you get a 500

<img width="1667" alt="screenshot 2019-01-24 at 18 39 32" src="https://user-images.githubusercontent.com/3748231/51700608-7e757e80-2007-11e9-9956-e24e9f3d8b24.png">

**Comment by BohoCode** [comment]
:-)

**Comment by qcastel** [comment]
This has been fixed by the OBIE directory team!
