### ISSUE TITLE
Barclays - 400 errors on account-requests endpoint

### ISSUE THREAD

**Issue by jspaine** [openbankingspace/tpp-issues#113]
Most requests to the account-requests endpoint are failing with 400 errors making new connections almost impossible.

Response body:
`"<html><head><title>JBWEB000065: HTTP Status 400 - </title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>JBWEB000065: HTTP Status 400 - </h1><HR size=\\"1\\" noshade=\\"noshade\\"><p><b>JBWEB000309: type</b> JBWEB000067: Status report</p><p><b>JBWEB000068: message</b> <u></u></p><p><b>JBWEB000069: description</b> <u>JBWEB000120: The request sent by the client was syntactically incorrect.</u></p><HR size=\\"1\\" noshade=\\"noshade\\"></body></html>"`

### Impact
Critical

#### Reference
OBSD-6501

**Comment by andreypanin** [comment]
I noticed this too today. Repeating the request sometimes helps. I also noticed that there are less errors if one is using v2.0 or the API (rather than v1.1 like myself).

**Comment by tobypinder** [comment]
@jspaine Barclays claimed to have resolved this on Thursday - we're no longer seeing it in our testing. Are you happy to close as resolved?

**Comment by jspaine** [comment]
Yep, last we saw it was on the 5th
