### ISSUE TITLE
HSBCG - 502 Bad Gateway for all Client Credential calls

### ISSUE THREAD

**Issue by tobypinder** [openbankingspace/tpp-issues#114]
# 502 Bad Gateway for all Client Credential calls

All Client Credential calls fail with the following `502` response.

```json
{"description":"Bad Gateway"}
```

## Impact

All PSUs unable to start a consent journey and therefore use Open Banking services across both HSBC and First Direct.

## References

[OBSD-6535](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-6535)

**Comment by tobypinder** [comment]
Service was interrupted at 10:18am and appeared restored at 10:46am, will update this issue with any post-hoc findings.

**Comment by oliver-hohn** [comment]
Re-opening as we are seeing the same exact issue since 1:16PM Today.

**Comment by AndyStabler** [comment]
From HSBC

> Thanks for heads up. We have a forgerock server down and teams working to bring it back up. We’ve raised a bug ticket with OBIE so comms should be going out.

**Comment by AndyStabler** [comment]
This issue is resolved for us now

**Comment by oliver-hohn** [comment]
For us as well, I think we can close this ticket now.
