### ISSUE TITLE
LBG - Product endpoint returning 503s (Service Unavailable)

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#116]
# LBG - Product endpoint returning 503s (Service Unavailable)

We are seeing 503 status codes being returned whenever we try to fetch products for any of the Lloyds Banking Group brands. We started seeing this issue at around 3:10am today (8th of February).

For example, a `GET` to `https://secure-api.lloydsbank.com/prod01/lbg/lyds/open-banking/v1.1/accounts/AccountId/product` leads to the following error response:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
```

## Impact

Very High. Any TPP that relies on account product information cannot obtain it.

Submitted as [OBSD-6617](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-6617).

**Comment by oliver-hohn** [comment]
LBG:
> Issue investigation is underway as a high priority to recover this service

**Comment by tobypinder** [comment]
LBG:
> Service was fully recovered on the 09th Feb at 23:28.

**Comment by jh-a** [comment]
@tobypinder - still seeing a relatively high failure rate across v1 and v2 product endpoints - please could you reopen this issue. 

JHA
