### ISSUE TITLE
Barclays - "Next" link points to itself

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#122]
When fetching the transactions of an account, on the first page, the one obtained via a `GET` to `accounts/AccountId/transactions`, the `Next` link points to the same page as the current page:
```json
{
  "Data": {
    "Transaction": [...]
  },
  "Links": {
    "First": "https://deimos.api.barclays/open-banking/v1.1/accounts/{AccountId}/transactions?toBookingDateTime=2019-02-27&offset=0&fromBookingDateTime=2017-02-27&includePendingRecords=true",
    "Next": "https://deimos.api.barclays/open-banking/v1.1/accounts/{AccountId}/transactions?toBookingDateTime=2019-02-27&offset=1&fromBookingDateTime=2017-02-27&includePendingRecords=false",
    "Self": "https://deimos.api.barclays/open-banking/v1.1/accounts/{AccountId}/transactions?toBookingDateTime=2019-02-27&offset=1&fromBookingDateTime=2017-02-27&includePendingRecords=false"
  },
  "Meta": {}
}
```

As can be seen from the above, the `Next` and `Self` links match.

After following the `Next` link, this issue persists as, again, the `Next` and `Self` links match, e.g.:
```json
{
    "Data": {
      "Transaction": [ ... ]
    },
    "Links": {
      "First": "https://deimos.api.barclays/open-banking/v1.1/accounts/{AccountId}/transactions?toBookingDateTime=2019-02-27&offset=0&fromBookingDateTime=2017-02-27&includePendingRecords=true",
      "Next": "https://deimos.api.barclays/open-banking/v1.1/accounts/{AccountId}/transactions?toBookingDateTime=2019-02-27&offset=51&fromBookingDateTime=2017-02-27&includePendingRecords=false",
      "Self": "https://deimos.api.barclays/open-banking/v1.1/accounts/{AccountId}/transactions?toBookingDateTime=2019-02-27&offset=51&fromBookingDateTime=2017-02-27&includePendingRecords=false"
    },
    "Meta": {}
  }
```

## Impact

Critical. This issue causes duplicate transactions being returned, and as no `TransactionId`s are provided, there is no way for a TPP to _safely_ deduplicate the returned transactions.

This ultimately results in TPPs being completely unable to utilise transaction information, as the presence of duplicated transactions in stored resources cannot be deduplicated without stable transaction identifiers. Thus TPPs will ingest this data incorrectly, resulting in potentially damaging and incorrect outcomes for PSUs using AISP services.

## References
Submitted as [OBSD-7053](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-7053).

**Comment by tobypinder** [comment]
This was fixed yesterday - we are keeping an eye out to see if anything recurs but looks good so far.
