### ISSUE TITLE
Barclays - PSU cannot consent because their Barclays Mobile Banking app is not the "latest"

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#137]
We've encountered an issue where, it seems like, the PSU has the most up-to-date version of the Barclays Mobile Banking application (v1.84, 2164), because on the Google Play Store this the latest version available to the PSU, however after typing in the 6-digit code, for the decoupled web-to-mobile journey, they are presented with the following error:
> OBA18
> We've updated the app so it's more useful and simpler to use. You'll need to down the latest version from the App Store before you can continue.

## Impact
High. This affects an unknown cohort of PSUs, and prevents them from sharing consent via Open Banking.

Submitted as [OBSD-7435](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-7435).

**Comment by tobypinder** [comment]
Resolved with Version 1.86.2166
