### ISSUE TITLE
Barclays - Client Credentials Grants failing with 401s

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#140]
Since, at least, 9:40 AM Today (15th March 2019), our Client Credential Grants have been failing with a 401 status code, and the following response body:
```json
{"error_description":"Invalid client or client credentials.","error":"invalid_client"}
```

We noticed this issue when we were checking on whether the issues: [OBSD-7443](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-7443) (https://github.com/openbankingspace/tpp-issues/issues/137) and [OBSD-7435](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-7435) (https://github.com/openbankingspace/tpp-issues/issues/138) had been resolved.

## Impact

Critical. With failing Client Credential Grants, it's not possible for a TPP to use OB.

Submitted as [OBSD-7457](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-7457).

**Comment by oliver-hohn** [comment]
We are now seeing 400 errors with the following body:
```json
{"error_description":"TPP Validation Failed","error":"invalid_grant"}
```

**Comment by tobypinder** [comment]
Resolved.
