### ISSUE TITLE
Open Banking Directories - Cannot submit OB WAC and OB Seal CSRs

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#146]
We are unable to submit "OB WAC" and "OB Seal" CSRs, in both the "Production" and "Production Test" directories using the instructions on the page:
```
The easiest option is to use OpenSSL. Just copy the following command to your command line. It will generate 2 files; a private key and a certificate signing request.

openssl req -new -newkey rsa:2048 -nodes -out [STATEMENT_CLIENT_ID].csr -keyout [STATEMENT_CLIENT_ID].key -subj "/C=GB/ST=/L=/O=OpenBanking/OU=[ORGANISATION_ID]/CN=[STATEMENT_CLIENT_ID]" -sha256
```

_Please note that we've redacted the STATEMENT_CLIENT_ID and ORGANISATION_ID above._

After pressing "Upload" we received an error dialog box, and we used the "Copy Message" functionality, which copied the following:
```
request_uuid: not provided
status: failure
message: We were unable to create or upload your certificate. Please try again.
created_at: 2019-03-27T11:42:36.331Z
```

We've also inspected the network requests, and it seems that a 500 response is returned by the GraphQL server used by the directory. The following error response body is returned for that request:
```json
{"errors":[{"message":"Error: Request failed with status code 400","locations":[{"line":2,"column":3}],"path":["addCertificate"]}],"data":null}
```

Is this a known issue?

Submitted as [OBSD-7768](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-7768).

**Comment by oliver-hohn** [comment]
We got this working in the end by changing our field orders in the certificate. We weren't using the given openssl config files.

**Comment by chrisshennan** [comment]
I'm experiencing the same issue.  Can you provide any more information on how you changed your field order?

**Comment by hatstand** [comment]
See https://github.com/creditkudos/eidas#notes-on-csr-format

**Comment by foyss** [comment]
> We got this working in the end by changing our field orders in the certificate. We weren't using the given openssl config files.

Hi, how did you fix this exactly? I'm having the same exact error too

**Comment by jekabolt** [comment]
@hatstand 404 :(

**Comment by jekabolt** [comment]
Any update on this issue?

**Comment by hatstand** [comment]
@jekabolt fixed

**Comment by oliver-hohn** [comment]
> > We got this working in the end by changing our field orders in the certificate. We weren't using the given openssl config files.
> 
> Hi, how did you fix this exactly? I'm having the same exact error too

@foyss please see https://github.com/creditkudos/eidas#notes-on-csr-format.

**Comment by jekabolt** [comment]
@hatstand @oliver-hohn  generated .csr using this tool. And I still have error :

``request_uuid: not provided
status: failure
message: We were unable to create or upload your certificate. Please try again.
created_at: 2019-10-29T14:17:21.947Z``

gen like this:
``go run cmd/cli/*.go -country-code GB   -organization-name "my org"   -organization-id PSDGB-OB-FCAGBR-000000 -common-name 0015800001041ORGID``

**Comment by hatstand** [comment]
That `organization-id` looks wrong at least, should be more like `PSDGB-FCA-123456`.

**Comment by jekabolt** [comment]
@hatstand tried ``go run cmd/cli/*.go -country-code GB   -organization-name "my org"   -organization-id PSDGB-FCA-123456 -common-name 0015800001041ORGID `` but still same error

**Comment by hatstand** [comment]
It's possible you need to use real values that match your TPP for those flags.

**Comment by jekabolt** [comment]
@hatstand  `` go run cmd/cli/*.go -country-code GB   -organization-name "Mia Pago Ltd"   -organization-id PSDGB-FCA-123456 -common-name 0015800001041ReAAI `` I used the real ones
