### ISSUE TITLE
Santander - Account Requests failing on the 18th of April

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#155]
At 6:18AM Today (18th of April), we had a period where our Account Requests were failing with a 401 status code, and the following error message:
```json
{"httpCode":"401","httpMessage":"Unauthorized","moreInformation":"Not registered to plan"}
```

We are no longer seeing this issue, since ~9:50AM Today. However, are Santander in a position to a provide a PSU facing explanation for the outage? We are pressed by PSUs and clients for explanations of various downtime windows, so it's critical that we can provide an accurate response to provide explanation when such outages occur.

Submitted as [OBSD-8285](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-8285).

**Comment by BillForster** [comment]
Update -incorrect/missing token being submitted in the failing requests which results in the 401s.

**Comment by oliver-hohn** [comment]
We aren't seeing this issue anymore, even though we haven't made any changes. For now, we are closing this.
