### ISSUE TITLE
Barclays - Refresh tokens not accepted even though AccountRequest is `Authorised` and not expired

### ISSUE THREAD

**Issue by hatstand** [openbankingspace/tpp-issues#167]
## Expected
Refresh token is valid for renewing an access token as long as the AccountRequest is "Authorised" and not expired.

## Actual
Refresh token is rejected even though AccountRequest is valid.

## Impact
We are unable to refetch transaction data for this and other affected accounts.

## Remediation
Accept refresh tokens to renew access tokens as long as AccountRequest is "Authorised" and not expired.

_Sent separately with request logs to Barclays_

**Comment by oliver-hohn** [comment]
Submitted as [OBSD-9381](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-9381).

**Comment by oliver-hohn** [comment]
This was due to an issue on the TPP side.
