### ISSUE TITLE
Barclays - Fetch failure for all endpoints excluding accounts in V3 

### ISSUE THREAD

**Issue by lucas-s-work** [openbankingspace/tpp-issues#173]
All attempts to fetch from Barclays OBV3 endpoints other than accounts fails with status code 400 and the following error.
```json 
{
  "Code": "400 Bad Request",
  "Id": "---",
  "Message": "Consent validation failed. ",
  "Errors": [
    {
      "ErrorCode": "UK.OBIE.Field.Unexpected",
      "Message": "Consent validation failed because of invalid data. "
    }
  ]
}
```

# Impact
High, this prevents usage of Barclays in V3.

Submitted as: **OBSD-9871**

**Comment by oliver-hohn** [comment]
Barclays deployed a fix on the 31st of July. This seems to have fixed the issue as it cannot be replicated anymore.
