### ISSUE TITLE
Barclays: Specific PSU resource `400` request errors (SO, DD, B)

### ISSUE THREAD

**Issue by tobypinder** [openbankingspace/tpp-issues#18]
A specific PSU is encountering `400` errors when requesting _Beneficiaries_, _Standing Orders_ and _Direct Debits_. 

For the PSU, an example body response is below

#### Body

Response code: `400`

```html
<html><head><title>JBWEB000065: HTTP Status 400 - </title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>JBWEB000065: HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000067: Status report</p><p><b>JBWEB000068: message</b> <u></u></p><p><b>JBWEB000069: description</b> <u>JBWEB000120: The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"></body></html>
```

Other PSUs are able to access these resources without issue, so I believe it must be tied to the configuration of that particular consumer.

## Impact

Very high: unknown cohort of PSUs unable to access Open Banking AIS. Retries and repeated consents do not resolve the issue.

## Remediation

Address underlying problem. `The request sent by the client was syntactically incorrect.` appears to refer to internal communication to/from the edge network rather than from TPPs as nothing about our requests is abnormal.

#### References
* [OBSD-4300](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-4300)

**Comment by tobypinder** [comment]
Barclays investigation concluded that the PSU doesn't exist (?) which conflicts with the fact that the other endpoints work, the PSU is known to us and it would be generally unreasonable for a non-user to "use" Account Information Services. We're trying to get clarification, and we'll attempt to contact the PSU for redemonstration of the behaviour.

**Comment by tobypinder** [comment]
A fix was apparently deployed but some time after we appeared to experience the same issue. As of day we've provided Barclays with new identifiers for them to reinvestigate and the OBSD issue remains open.

**Comment by tobypinder** [comment]
Fix deployed on Monday, we are unable to confirm without access to a PSU that triggered this issue but will reopen if we experience regression.

**Comment by oliver-hohn** [comment]
We are re-opening this (and the OBSD issue [OBSD-4300](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-4300)), due to a re-occurrence over the weekend.

**Comment by tobypinder** [comment]
A second fix was deployed on the 18th November, we are unable to confirm without access to a PSU that triggered this issue but will reopen if we experience regression.
