### ISSUE TITLE
Barclays - Consent Management unavailable in App

### ISSUE THREAD

**Issue by tobypinder** [openbankingspace/tpp-issues#21]
App based consent management appears to be down. On the mobile app's "Third Party permissions" page, the following options result in a blank, white screen after loading: 

* Permission control centre
* Manage Third Party Permissions
* Permission history

This has been tested using Android but we believe both mobile platforms would be impacted.

## Impact

This means that a PSU cannot manage their consents or enable access to Open Banking if they have additional roadblocks set for themselves such as

* Manually disabling the "Allow my data to be shared" toggle
* Being a joint account and therefore subjected to the additional joint-accounts preauthorisation step.

Therefore, a significant portion of PSUs cannot access the services, nor can _any_ PSU revoke consents.

**Comment by oliver-hohn** [comment]
According to Barclays this was an isolated incident to my mobile banking app. Following a retest today, the issue has been resolved.
