### ISSUE TITLE
Barclays - Authorization Server appears to be down

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#22]
When accessing the Authorization server, PSUs are greeted with the following unrecoverable error.

![screen shot 2018-07-31 at 10 40 34](https://user-images.githubusercontent.com/17027801/43453462-173e6140-94b2-11e8-81ed-4c9a930b7301.png)

## Impact

Critical. Open Banking is unavailable for all PSUs. Additionally, the error behaviour does not redirect back to the TPP with an Oauth error, which makes the error unrecoverable by the TPP (ie an alternative solution cannot be offered and the tab must be closed by the end user)

**Comment by tobypinder** [comment]
Issue accepted and being triaged by Barclays.

**Comment by tobypinder** [comment]
Issue appears to be resolved.
