### ISSUE TITLE
HSBCG - Specific PSU Product endpoint is returning 403s

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#24]
A PSU is experiencing issues fetching the product of their account. Consistent 403 responses are observed, even after "retrying" the endpoint.

For the PSU, an example response of the 403 response is:
```json
{"description":"Forbidden"}
```

We believe this may be due to an "edge-case" account product that fails HSBC validations when rendering the response.

## Impact

High. This affects an unknown cohort of PSUs unable to use the Open Banking AIS. Retries and repeated consents do not resolve the issue.

**Comment by jogu** [comment]
The PSU in this case is myself and I'm happy with work with HSBC to try and track this down...

**Comment by oliver-hohn** [comment]
HSBC have informed us that this has been fixed, @jogu could you try again?

**Comment by oliver-hohn** [comment]
Following HSBC informing that the fix has been deployed and @jogu retesting, it seems that this issue has been fixed. If it re-occurs this issue can be re-opened.
