### ISSUE TITLE
Barclays: Transactions endpoint returning malformed balances

### ISSUE THREAD

**Issue by tobypinder** [openbankingspace/tpp-issues#29]
A PSU is getting invalid responses from the transactions endpoint such that their Balance is being returned with a negative number. This field is intended to be unsigned, with TPPs using the `CreditDebitIndicator` to determine Credit or Debit status.

### Partially redacted example.

```js
{
  "AccountId" : "10000000000000000XXX",
  "Amount" : {
    "Amount" : "21xx.xx",
    "Currency" : "GBP"
  },
  "Balance" : {
    "Amount" : {
      "Amount" : "-396.xx",
      "Currency" : "GBP"
    },
    "CreditDebitIndicator" : "Debit",
    "Type" : "Information"
  },
  "BookingDateTime" : "2018-07-30Txx:xx:xx+01:00",
  "CreditDebitIndicator" : "Debit",
  "Status" : "Booked",
}
```

The `OBReadTransaction1/Data/Transaction/Amount` here is incorrect as this is an unsigned field that must conform to `^\d{1,13}\.\d{1,5}$`. The `CreditDebitIndicator` is intended to provide signage, with the `Amount` simply denoting magnitude. 

## Impact

Very High. TPPs cannot reasonably ingest this data nor build workarounds, as it is inherently unclear whether a "negative debit" is intended to be a "credit", or if the signage simply wasn't stripped and this is actually intended to be a debit. 

It is unknown what cohort of users are affected by this behaviour, but we feel it is reasonable to assume unless otherwise confirmed that all negative balances would be impacted.

## Remediation

Ensure Currency "Amount" fields never contain signs.

**Comment by oliver-hohn** [comment]
We continue to see signed balance amounts for transactions. We have asked Barclays on a progress update for the fix.

**Comment by tobypinder** [comment]
This is now fixed in Barclays' production environment.
