### ISSUE TITLE
LBG: PSU Standing Order contains an invalid "Frequency" definition. 

### ISSUE THREAD

**Issue by tobypinder** [openbankingspace/tpp-issues#30]
According to the [Account and Transaction API v1.1 spec](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/5785171/Account+and+Transaction+API+Specification+-+v1.1.0), The Standing Order "Frequency" field (`OBReadStandingOrder1/Data/StandingOrder/Frequency`)

#### Frequency Regex

`^(EvryDay)$|^(EvryWorkgDay)$|^(IntrvlWkDay:0[1-9]:0[1-7])$|^(WkInMnthDay:0[1-5]:0[1-7])$|^(IntrvlMnthDay:(0[1-6]|12|24):(-0[1-5]|0[1-9]|[12][0-9]|3[01]))$|^(QtrDay:(ENGLISH|SCOTTISH|RECEIVED))$`

(This is perhaps better visualised as below)
![image](https://user-images.githubusercontent.com/618992/43855722-6f4296d0-9b3e-11e8-9482-34a1d85bc697.png)

However, Halifax returned a "Frequency" of `IntrvlWkDay:01:00` which is invalid. As the second pair of digits corresponds with the day of the week of the payment (01-07), a value of `00` is non-sensical.

## Impact

High. An unknown cohort of PSUs cannot access account information services that parse standing order information, as the information that is presented by the API violates the spec and has no "meaning" that we can assign as a workaround on our side. Repeated attempts will not change the customer outcome, as the data remains immutable between consent requests.

## Remediation

Change API endpoint to only return Frequencies aligned to the frequency regex. 

---

**Comment by tobypinder** [comment]
Fix identified, fix ETA unknown.

**Comment by oliver-hohn** [comment]
According to LBG:
> The fix was deployed to Production yesterday (2nd of October)

As this was a PSU specific issue, we cannot retest that the fix is in, so we will close the ticket, and re-open it in the case we see another occurrence of this.
