### ISSUE TITLE
 Barclays - Mobile and Web App - Open Banking "Management System" is down

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#33]
As of today (14th of August 2018) at 9:52am, the Barclays Mobile Banking App (v1.68) Open Banking management systems ("Permission control centre", "Manage third-party permissions", and "Permission history"), under "More" > "Settings" > "Third-party permissions", are unavailable. On the Barclays Online Banking web page, under "Privacy and data permissions", the "Manage third party permissions" system is also unavailable. Both the mobile app and web page render the same error message when trying to use these systems:
> Some technical exception has occurred. Please contact helpdesk for assistance.

With these issues it is not possible for a PSU to revoke consent from a TPP from their Banking interface through the "Manage third-party permissions" option. It is also not possible to authorize the sharing of Barclays' joint accounts as these require authorization from all holders of the joint account through the "Permission control centre" option.

## Impact

High. This does not allow PSUs to revoke or manage consent from their Banking interfaces.

## Remediation

Introduce the functionality of managing consent again by fixing the "technical exception" seen on the Mobile Banking and Online Banking Apps. 

## Resources

* [Account and Transaction API Specification v1.1.0](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/5785171/Account+and+Transaction+API+Specification+-+v1.1.0)

**Comment by tobypinder** [comment]
Issue accepted by Barclays

**Comment by tobypinder** [comment]
Downtime appears resolved. Will update if given information.
