### ISSUE TITLE
Barclays: Consent instructions are incorrect.

### ISSUE THREAD

**Issue by tobypinder** [openbankingspace/tpp-issues#37]
# Consent instructions are incorrect.

PSUs are given incorrect information on how to access consent interfaces in Barclays mobile and web interfaces. Both of these instructions are deficient, and lead to signficant PSU confusion.

### Mobile

![consent_instructions_incorrect mob](https://user-images.githubusercontent.com/618992/44160374-26c70480-a0b2-11e8-90e6-2f0bfd0e9366.png)

As seen above, the authorization server indicates that PSUs should access

`More > Data and Privacy > Third-party permissions > Give your permission`

However to access the Consent granting interface, PSUs must actually access

`More > Settings > Third-party permissions > Give your permission`

### Web

![consent_instructions_incorrect web](https://user-images.githubusercontent.com/618992/44160387-2d557c00-a0b2-11e8-8996-3df9552fd947.png)

As seen above, the authorization server indicates that PSUs should access

`Select Profile > Privacy and data permissions > Give third-party permission`

However, in practice there is no section labelled "Profile" - regardless of any internal naming this is opaque to users and it's not clear how they would be expected to understand that the highlighted section of the page below is the "Profile".

![consent_instructions_incorrect web ui1](https://user-images.githubusercontent.com/618992/44160399-32b2c680-a0b2-11e8-8a19-9a3d1929f7dc.png)

![consent_instructions_incorrect web ui2](https://user-images.githubusercontent.com/618992/44160403-36464d80-a0b2-11e8-89ac-b5ccbe8f9d74.png)

## Impact

Critical. Credit Kudos is of the position that we cannot go live with an integration that gives erroneous and/or incomplete instructions to PSUs without expecting significant drop-off. We also feel this would be construed as an "obstacle to the provision of [services]" under _RTS Article 32 (3)_ in the current form.

## Remediation

Revise instructions given to PSUs.

**Comment by jspaine** [comment]
Have you reported this on OBSD?

**Comment by jh-a** [comment]
Yes, and to Barclays directly. Several times.

**Comment by tobypinder** [comment]
@jspaine All issues here are on OBSD - this is [OBSD-4580](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-4580). Going forward I intend to add the OBSD references in the original submissions to aid tracking through the OB provided [Current Issues](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/504496461/Current+Issues) page.

**Comment by tobypinder** [comment]
Retesting to confirm fix

**Comment by oliver-hohn** [comment]
We've retested this, and Barclays have updated the instructions to match the UI options. As such we are closing the issue.
