### ISSUE TITLE
[Ozone] - Sandbox Modelo response includes undefined for Identification field

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#42]
When fetching the `Accounts` from Modelo, one of the accounts, with `AccountId` `500000000000000000000007`, has an `Account/Identification` field, for a `SortCodeAccountNumber` `SchemeName`, where the sort code value is `undefined`. While the specification does not define the format for this value, we believe a sort code of `undefined` is not desired in the Modelo implementation.

## Expected Response

```json
{
  "Data":{
    "Account":[
      {
        "AccountId":"500000000000000000000001",
        "Currency":"GBP",
        "Nickname":"xxxx0101",
        "Account":{
          "SchemeName":"SortCodeAccountNumber",
          "Identification":"10000119820101",
          "Name":"Mr. Roberto Rastapopoulos & Mr. Mitsuhirato",
          "SecondaryIdentification":"Roll No. 001"
        }
      },
      {
        "AccountId":"500000000000000000000007",
        "Currency":"GBP",
        "Nickname":"xxxx0001",
        "Account":{
          "SchemeName":"SortCodeAccountNumber",
          "Identification":"01010190210001",
          "Name":"Marios Amazing Carpentry Supplies Limited"
        }
      }
    ]
  },
  "Links":{
    "Self":"/open-banking/v1.1/accounts?"
  },
  "Meta":{
    "TotalPages":1
  }
}
```

## Actual

```json
{
  "Data":{
    "Account":[
      {
        "AccountId":"500000000000000000000001",
        "Currency":"GBP",
        "Nickname":"xxxx0101",
        "Account":{
          "SchemeName":"SortCodeAccountNumber",
          "Identification":"10000119820101",
          "Name":"Mr. Roberto Rastapopoulos & Mr. Mitsuhirato",
          "SecondaryIdentification":"Roll No. 001"
        }
      },
      {
        "AccountId":"500000000000000000000007",
        "Currency":"GBP",
        "Nickname":"xxxx0001",
        "Account":{
          "SchemeName":"SortCodeAccountNumber",
          "Identification":"undefined90210001",
          "Name":"Marios Amazing Carpentry Supplies Limited"
        }
      }
    ]
  },
  "Links":{
    "Self":"/open-banking/v1.1/accounts?"
  },
  "Meta":{
    "TotalPages":1
  }
}
```

**Comment by fgyara2** [comment]
This is certainly an issue and it will be addressed by 03-Aug-18.

Could someone please add me to the repo so that Ozone issues can be assigned to me.

**Comment by tobypinder** [comment]
@fgyara2 I still can't seem to assign this - not sure why as I thought you'd been added. Worth mentioning that it's concurrently submitted as [OBSD-4739](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-4739) so if the OBSD is preferable, we just treat this as more of a public "shadowing" for interested TPPs/parties to collate issues

**Comment by fgyara2** [comment]
Not sure why - as long as you tag me, I will be able to see these and follow up - not a major issue

**Comment by fgyara2** [comment]
And fixed

**Comment by fgyara2** [comment]
@oliver-hohn - Could you check and mark this as fixed (I still do not have the neccessary access to fix issues)

**Comment by tobypinder** [comment]
Apologies for delay in responding to the fix on here, we're just confirming this now.

**Comment by oliver-hohn** [comment]
Can confirm that this has been fixed.
