### ISSUE TITLE
Ozone: Modelo returning "N/A" payloads for Balances.

### ISSUE THREAD

**Issue by tobypinder** [openbankingspace/tpp-issues#44]
# Ozone: Modelo returning "N/A" payloads for Balances.

As of yesterday, Modelo is returning erroneous responses in Balance payloads:

```js 
  "Balance":{
    "Amount":{
      "Amount":"NaN",
      "Currency":"GBP"
    }
  }
```

as far as we can tell this impacts the `/balance` and `/transactions` endpoints for V1, and is limited to Balance amount objects. 

Referenco does not appear to be impacted.

----

Submitted as [OBSD-4788](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-4788)

**Comment by fgyara2** [comment]
@tobypinder - On this. Please expect to be patched by the weekend.

**Comment by fgyara2** [comment]
Sorry - this took a little longer than expected.

I have put out a patch now and it should work as per spec.

**Comment by oliver-hohn** [comment]
We've retested the issue, and we can confirm that it has been fixed, so we are happy to close the issue.
