### ISSUE TITLE
Ulster Bank - Standing Order endpoint returning 500 for PSU

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#45]
A production PSU is experiencing an issue when sharing their Standing Orders with us. The endpoint consistently returns a 500 response status code with no response body.

## Impact

High. This affects an unknown cohort of PSUs, and prevents them from sharing their Standing Orders. In addition, we believe that the error response should include a body to provide more information on what caused the error.

## Other ticket links
- OBSD-4817: https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-4817
- NWSD-79: https://rbsgroupapiservicedesk.spectrumhosting.net/plugins/servlet/desk/portal/2/NWSD-79

**Comment by oliver-hohn** [comment]
According to RBSG the issue:
> ... affects all users who have Standing Orders that have expired (i.e. Standing Orders that have reached the end of their initial duration and that have no frequency date set).

Fix is expected to be deployed at the end of November

**Comment by tobypinder** [comment]
Fix now expected 6th November

**Comment by tobypinder** [comment]
Fix was applied on the 15th November.
