### ISSUE TITLE
Barclays - Accounts endpoint returns 400 HTML error response

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#52]
A specific PSU is encountering `400` errors when requesting Accounts. The issue may be linked to [OBSD-4300](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-4300)/https://github.com/openbankingspace/tpp-issues/issues/18 as the behaviour seems to be similar due to both issues responding with a 400 status code and, what looks like, the same HTML error response body:
```html
<html><head><title>JBWEB000065: HTTP Status 400 - </title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>JBWEB000065: HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000067: Status report</p><p><b>JBWEB000068: message</b> <u></u></p><p><b>JBWEB000069: description</b> <u>JBWEB000120: The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"></body></html>
```

## Impact

Very high: unknown cohort of PSUs unable to access Open Banking AIS. Retries and repeated consents do not resolve the issue.

## Remediation

Address underlying problem. The request sent by the client was syntactically incorrect. appears to refer to internal communication to/from the edge network rather than from TPPs as nothing about our requests is abnormal.

**Comment by oliver-hohn** [comment]
Following the PSU retesting, it seems that the issue has not been resolved as we receive the same 400 error response when fetching `/accounts`

**Comment by tobypinder** [comment]
Barclays response:

> We are currently testing the required fix and will confirm a deployment date for resolution once testing has concluded

**Comment by oliver-hohn** [comment]
Following Barclays' confirmation of deployment:
>  I wanted to let you know that following a successful deployment overnight (*18th October*) we are pleased to confirm the above issue has now been resolved and as such customers should no longer see this error
> 
> The issue was linked directly with the Regular Payment endpoint and if you are able to test this and confirm the issue no longer exists we will look to close this down


We are unable to track down the original PSU at this time, as such we are happy to close this ticket, and will re-open it if the issue re-occurs.
