### ISSUE TITLE
HSBC business openbanking seems to be down

### ISSUE THREAD

**Issue by jogu** [openbankingspace/tpp-issues#57]
Trying to link by business current account to Yolt via openbanking just fails on the first step of the HSBC web site, showing "We're sorry, this service is temporarily unavailable" as per below screenshot.

It's been doing this for at least an hour consistently, I've been unable to progress past the first step that asked for my username+security code after multiple attempts.

![image from ios](https://user-images.githubusercontent.com/316456/45687555-0e318a80-bb47-11e8-80b4-b7b458a778e5.png)

**Comment by tobypinder** [comment]
Indication from Slack that this is a V2 specific issue - rather than specific to business.

**Comment by tobypinder** [comment]
Did this get resolved?

**Comment by jogu** [comment]
I just tried the Yolt iOS app again and was able to successfully pair my HSBC business account this time.

As an end user, it's hard to know if it's fixed or if this is part of the generally instability that seems to affect HSBC business accounts and it just happens to be working right now.

**Comment by tobypinder** [comment]
@jogu Agreed. For now  I will close this issue as it appears to have "resolved" but there is a clear industry need for greater transparency around ASPSP downtimes and service degradation - it's something that we're looking at both with OBIE involvement and as a collection of TPPs to address.
