### ISSUE TITLE
Create payment request api returning 403 forbidden

### ISSUE THREAD

**Issue by purvak22** [openbankingspace/tpp-issues#66]
Hi,
I am trying to run the postman collection shared by ForgeRock for Example 2: Payment flow. 
I am following the below document : 
https://docs.ob.forgerock.financial/

I have successfully run first 2 calls - "Generate client credentials JWT" and "Client Credential", when trying to execute the next one - "Create payment request", I am getting the following response - 
{
    "timestamp": "2018-10-02T07:06:08.673Z",
    "status": 403,
    "error": "Forbidden",
    "message": "Forbidden",
    "path": "/open-banking/v2.0/payments"
}

The postman collection (Example 2: Payment flow) which I am using is here : 
https://raw.githubusercontent.com/ForgeRock/ForgeRock-OpenBanking-Sample/master/postman/OpenBanking%20Sample.postman_collection.json

can you please help?

Thanks,
Purva

**Comment by qcastel** [comment]
Hello Purva,

This github space is more reserved for issue, not support questions. 
For support, we use the Open Banking UK slack (http://signup.openbanking.space/) where we got a dedicated support channel #forgerock_support.

Will be happy to answer/help in that channel.

In the mean time, I will close this issue as this kind of questions would be address in the slack channel instead.

Thanks,

Quentin
