### ISSUE TITLE
Barclays - Negative Balances are being signed

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#73]
We have PSUs with what we assume is a negative balance, based on the `creditDebitIndicator` being `debit`, and a `Balance/Amount/Amount` that is signed to be a negative value. According to the [Account and Transaction API Specification v1.1.0 "Balances" section](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/5785171/Account+and+Transaction+API+Specification+-+v1.1.0), the `Balance/Amount/Amount` is defined by the following regex: `^\d{1,13}\.\d{1,5}$`. This regex indicates that the `Balance/Amount/Amount` is **unsigned** and that the `Balance/Amount/CreditDebitIndicator` indicates whether the value is negative, by setting `CreditDebitIndicator` to `debit`, and whether it is positive, by setting `CreditDebitIndicator` to `credit`.

This issue seems to be tied to [OBSD-4421](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-4421)/https://github.com/openbankingspace/tpp-issues/issues/29, as in that issue the `Balance/Amount` of a `Transaction` was also being signed. 

## Impact

Critical. TPPs cannot reasonably ingest this data nor build workarounds, as it is inherently unclear whether a "negative debit" is intended to be a "credit", or if the signage simply wasn't stripped and this is actually intended to be a debit.

It is unknown what cohort of users are affected by this behaviour, but we feel it is reasonable to assume unless otherwise confirmed that all negative balances would be impacted.

## Remediation

* Ensure `Balance/Amount/Amount` never contains a signed value.
* Immediately provide guidance to TPPs about which way they should interoret signed values given the current system so a safe parsing workaround can be implemented.
* Complete an evaluation on other `Amount` objects throughout the Resource Payloads to ensure that every possible value is unsigned.

Submitted as [OBSD-5351](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-5351).

**Comment by oliver-hohn** [comment]
Barclays have deployed the fix to their application yesterday evening.

**Comment by oliver-hohn** [comment]
Re-opening this as the issue has surfaced again. Awaiting Barclays' response.

**Comment by oliver-hohn** [comment]
Fix to be deployed early this week (3rd December).

**Comment by jspaine** [comment]
Any news about this being fixed? We're just getting a couple of reports that sound like they could be caused by this.

**Comment by oliver-hohn** [comment]
@jspaine We've requested an update from Barclays on the status of this fix. Waiting to hear back.

**Comment by oliver-hohn** [comment]
@jspaine We've received confirmation from Barclays that the fix has been deployed. We've investigated new payloads, and can confirm that negative balances are not being signed anymore, and that the `creditDebitIndicator` is being set to `Debit` to identify these negative balances.

**Comment by jspaine** [comment]
Ok, thanks @oliver-hohn
