### ISSUE TITLE
Barclays - 509 error response and logout when trying to give consent on the Online Banking webpage

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#83]
Follows on from https://github.com/openbankingspace/tpp-issues/issues/70.

In https://github.com/openbankingspace/tpp-issues/issues/70 the user was logged out immediately after pressing "Give third party permissions". This has been fixed, but now the user experiences a 509 error response and logout after entering the 6-digit code and pressing the "Get Started" button. See the error response below:
![screenshot 2018-11-23 at 11 21 18](https://user-images.githubusercontent.com/17027801/49010382-fab82680-f16a-11e8-96b4-942e5286252c.png)

**Note: the user had just logged in moments ego, and not 10 minutes ago like the error response suggests.**

## Impact

Critical. This affects an unknown cohort of Barclays customers, and prevents them from sharing data via Open Banking.

Opened as [OBSD-5758](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-5758).

**Comment by oliver-hohn** [comment]
Barclays response:
> this was an intermittent issue and we believe the issue to be resolved as part of the broader changes we have implemented in Online Banking that also corrected the 501 error.

As the user is not experiencing this error anymore, we are closing this.

**Comment by narkan** [comment]
I am having this issue, and getting logged out when clicking on "Give third party permissions" to authorise my accounting software to connect. 

![Screenshot 2021-01-18 at 11 52 51 1](https://user-images.githubusercontent.com/3526836/104927421-4ce6e200-5999-11eb-83d7-5e3130890db0.png)
