### ISSUE TITLE
LBG: State parameter not played back in the redirect to the TPP during authorisation failure 

### ISSUE THREAD

**Issue by j-ahmed** [openbankingspace/tpp-issues#9]
`State` is not played back in the redirect to the TPP if the authorisation results in cancellation or failure. 
We have observed this occurring in the following scenarios;
* If pressed cancelled during consent authorisation at the bank’s authorisation page (Cancel and go back to "TPP").
* During any kind of redirection failure, eg: when an error is appened to the query parameters on the callback `?error=400`

According to the OB Security Profile, the `state` parameter is mandatory if provided
> If the parameter is provided, the ASPSP MUST play-back the value in the redirect to the TPP.

**Comment by jspaine** [comment]
Lloyds have said this is fixed, it's working for us.

**Comment by tobypinder** [comment]
Closing as appears to be resolved, reopen if it's not working for you @j-ahmed
