### ISSUE TITLE
Santander - Refresh token errors break connections

### ISSUE THREAD

**Issue by jspaine** [openbankingspace/tpp-issues#93]
We received 500 error codes from Santander's token endpoint this morning (between 10:11 and 10:14) while updating most (>75%) of our connections. The failed requests were retried automatically 10 min later when they again failed with 401.

It seems that our refresh tokens have been invalidated though we didn't receive new ones, and these connections will need to be re-authorised by our users.

# Reference
[OBSD-5912](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-5912)

**Comment by jspaine** [comment]
This has apparently been resolved between OB and Santander.

**Comment by tobypinder** [comment]
Did you ever get your consents reactivated or did you still lose access?

**Comment by jspaine** [comment]
No, everyone affected had to reauthorise.
