### ISSUE TITLE
RBSG - Natwest - PSUs Standing Orders endpoint returns 500 status codes

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#97]
We are unable to fetch a PSU's `StandingOrders` as the endpoint is returning 500 status codes and no body in the response.

This issue could be tied to the closed ticket [OBSD-4817](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-4817)  on the OBSD (https://github.com/openbankingspace/tpp-issues/issues/74 on GitHub).

## Impact

High. This affects an unknown cohort of PSUs, and prevents them from using Open Banking powered services that require Standing Order data.

Submitted as [OBSD-6048](https://openbanking.atlassian.net/servicedesk/customer/portal/1/OBSD-6048) on the OBSD, and as [NWSD-154](https://rbsgroupapiservicedesk.spectrumhosting.net/plugins/servlet/desk/portal/2/NWSD-154) on the RBSG service desk.

**Comment by tobypinder** [comment]
Still investigating but it appears this issue is related to the nightly 2:00-2:40 maintenance window that RBSG have.

**Comment by oliver-hohn** [comment]
RBS have a nightly 40 minute downtime between 2:00 and 2:40.
